let a = 10
let b = 20
let c = '10'
let d = 'ten'
let e = true
console.log(a < b); //true
console.log(a == b); //false
console.log(a > b); //false
console.log(a == c)  //true
console.log(a === c) //false
console.log(a > e)   //true